; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src/stopngo   ; ← change cette ligne pour switcher d'environnement'

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 9600

[env:MVP]
src_dir = src/MVP

[env:moy]
src_dir = src/moy

[env:distmax]
src_dir = src/distmax

[env:stopngo]
src_dir = src/stopngo